steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

# [START tg-plan]
- id: 'terragrunt plan'
  name: 'alpine/terragrunt:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        terragrunt plan
# [END tg-plan]

# [START tg-apply]
- id: 'terragrunt apply'
  name: 'alpine/terragrunt:latest'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |          
        terragrunt apply -auto-approve
        echo "***************************** Yeeeee *******************************"
        echo "Just yolo"
        echo "*******************************************************************************"
# [END tf-apply]  
options:
  logging: CLOUD_LOGGING_ONLY
